import type { Metadata } from "next";
import { QueryProvider } from "./_api/client";
import { UserDataProvider } from "./_api/client/UserDataProvider";
import { Layout } from "./_ui/Layout";
import "./globals.css";

export const metadata: Metadata = {
  title: "FSD-NextJS",
  description: "FSD Tutorial, Generated by create next app",
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="ko">
      <body>
        <QueryProvider>
          <UserDataProvider>
            <Layout>{children}</Layout>
          </UserDataProvider>
        </QueryProvider>
      </body>
    </html>
  );
}
